language: python
sudo: required
dist: trusty

python:
  - "3.8"

before_install:
  - sudo apt-get install default-jre r-base-dev -y

install:
  - python setup.py install

script: 
  - cd tests && echo $PATH
